// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package dauphine.projet.sar.server.RMI;

public final class ControleurRemoteImp_Stub
    extends java.rmi.server.RemoteStub
    implements dauphine.projet.sar.server.RMI.InterfaceControleurRemote, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_vitesseMoins_0;
    private static java.lang.reflect.Method $method_vitessePlus_1;
    
    static {
	try {
	    $method_vitesseMoins_0 = dauphine.projet.sar.server.RMI.InterfaceControleurRemote.class.getMethod("vitesseMoins", new java.lang.Class[] {int.class});
	    $method_vitessePlus_1 = dauphine.projet.sar.server.RMI.InterfaceControleurRemote.class.getMethod("vitessePlus", new java.lang.Class[] {int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public ControleurRemoteImp_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of vitesseMoins(int)
    public void vitesseMoins(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_vitesseMoins_0, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, 4692753105378022573L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of vitessePlus(int)
    public void vitessePlus(int $param_int_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_vitessePlus_1, new java.lang.Object[] {new java.lang.Integer($param_int_1)}, -439484241047378877L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
